services:
  mongo:
    image: mongo:7
    container_name: thesis-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  perl-parser:
    build: .
    container_name: thesis-parser
    volumes:
      - .:/app
    ports:
      - "8090:8090"
    stdin_open: true
    tty: true
    working_dir: /app
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB_NAME: thesis
      PYTHONUNBUFFERED: "1"

volumes:
  mongo_data:
